### ISSUE TITLE
没有响应

### ISSUE THREAD

**Issue by kirkluokun** [hxj8059/obsidian-cubox-import#1]
file path设置成obsidian/temp store/
cubox token已输入
但点击同步后没有响应
请问cubox网页端是否需要做什么设置？

**Comment by hxj8059** [comment]
同步的是cubox的归档文件夹，手机端暂时还用不了，pc/mac/linux都可以

**Comment by tzungtzu** [comment]
> 同步的是cubox的归档文件夹，手机端暂时还用不了，pc/mac/linux都可以

@hxj8059  感谢开发，我用了一下，的确可以同步归档文件夹的文章，但是好像又不是全部，请问是否有限制同步数量？另外想问下能否修改同步的文件夹呢？

**Comment by hxj8059** [comment]
> > 同步的是cubox的归档文件夹，手机端暂时还用不了，pc/mac/linux都可以
> 
> @hxj8059 感谢开发，我用了一下，的确可以同步归档文件夹的文章，但是好像又不是全部，请问是否有限制同步数量？另外想问下能否修改同步的文件夹呢？

新的release已经添加这些功能了 ，https://github.com/hxj8059/obsidian-cubox-import/releases/tag/0.9.0
