### ISSUE TITLE
同步归档文件夹只能同步50个，其他的都无法再同步了，请教下能否同步所有收藏呢？

### ISSUE THREAD

**Issue by Jinxxxxxxin** [hxj8059/obsidian-cubox-import#2]

**Comment by hxj8059** [comment]
准备修复，目前默认是50，因为能够覆盖最新的50条

**Comment by hxj8059** [comment]
新的release已经添加这些功能了 ，https://github.com/hxj8059/obsidian-cubox-import/releases/tag/0.9.0

**Comment by hxj8059** [comment]
New features solve the issue
